### ISSUE TITLE
🛑 WeezTarget is down

### ISSUE THREAD

**Issue by Weezevent-Ops** [Weezevent/status-page#23]
In [`96532d9`](https://github.com/Weezevent/status-page/commit/96532d93566c196996d093ae638c3ff49183af93
), WeezTarget (https://api.weezevent.com/target/_DOWN) was **down**:
- HTTP code: 404
- Response time: 546 ms

**Comment by bmunzer** [comment]
due to infrastructure provider we are not able to send emails since 16:00
