### ISSUE TITLE
🛑 Back-office is down

### ISSUE THREAD

**Issue by Weezevent-Ops** [Weezevent/status-page#24]
In [`86aae66`](https://github.com/Weezevent/status-page/commit/86aae667cb2f47fecb862f67c89a658c23f8fe04
), Back-office (https://www.weezevent.com/bo/_DOWN) was **down**:
- HTTP code: 404
- Response time: 521 ms

**Comment by bmunzer** [comment]
due to infrastructure provider we are not able to send emails since 16:00
