### ISSUE TITLE
🛑 Guichet / Ticket Office is down

### ISSUE THREAD

**Issue by Weezevent-Ops** [Weezevent/status-page#25]
In [`d855620`](https://github.com/Weezevent/status-page/commit/d85562039df8fb2bf5c574e4b722ca56d38139a0
), Guichet / Ticket Office (https://guichet.weezevent.com/_DOWN) was **down**:
- HTTP code: 403
- Response time: 796 ms

**Comment by bmunzer** [comment]
due to infrastructure provider we are not able to send emails since 16:00
