### ISSUE TITLE
🛑 Weezevent is down

### ISSUE THREAD

**Issue by Weezevent-Ops** [Weezevent/status-page#27]
In [`57090b5`](https://github.com/Weezevent/status-page/commit/57090b595ec7a8e904dbc0650b0a1bc9e257f94f
), Weezevent (https://weezevent.com/en-gb/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by bmunzer** [comment]
Today our showcase site weezevent.com had some down time. New hardware configuration has been setup to solve the issue. Any other crtical services were impacted. We apologize for the inconvinients.
