### ISSUE TITLE
Weezevent showcase website is down

### ISSUE THREAD

**Issue by darkwind-noveo** [Weezevent/status-page#34]
In [`b904960`](https://github.com/Weezevent/status-page/commit/b9049607e385f423d9a30c8d4402fff3a4aa4a6d
), Weezevent website (https://weezevent.com/en-gb/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by bmunzer** [comment]
Today our _showcase site_ weezevent.com had some down time. 
New hardware configuration has been setup to solve the issue.

Any other crtical services were impacted.

We apologize for the inconvinients.
